// <auto-generated />
using Beam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beam.Data.Migrations
{
    [DbContext(typeof(BeamContext))]
    [Migration("20260916152802_AddUserPasswords")]
    partial class AddUserPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Beam.Data.Frequency", b =>
                {
                    b.Property<int>("FrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FrequencyId");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("Beam.Data.Prism", b =>
                {
                    b.Property<int>("PrismId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrismId"));

                    b.Property<int>("RayId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PrismId");

                    b.HasIndex("RayId");

                    b.HasIndex("UserId");

                    b.ToTable("Prisms");
                });

            modelBuilder.Entity("Beam.Data.Ray", b =>
                {
                    b.Property<int>("RayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RayId"));

                    b.Property<int>("FrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RayId");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("UserId");

                    b.ToTable("Rays");
                });

            modelBuilder.Entity("Beam.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Beam.Data.Prism", b =>
                {
                    b.HasOne("Beam.Data.Ray", "Ray")
                        .WithMany("Prisms")
                        .HasForeignKey("RayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beam.Data.User", "User")
                        .WithMany("Prisms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ray");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Beam.Data.Ray", b =>
                {
                    b.HasOne("Beam.Data.Frequency", "Frequency")
                        .WithMany("Rays")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beam.Data.User", "User")
                        .WithMany("Rays")
                        .HasForeignKey("UserId");

                    b.Navigation("Frequency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Beam.Data.Frequency", b =>
                {
                    b.Navigation("Rays");
                });

            modelBuilder.Entity("Beam.Data.Ray", b =>
                {
                    b.Navigation("Prisms");
                });

            modelBuilder.Entity("Beam.Data.User", b =>
                {
                    b.Navigation("Prisms");

                    b.Navigation("Rays");
                });
#pragma warning restore 612, 618
        }
    }
}
