name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: pennsignals/publish_docker-compose@v0.1.1
      with:
        docker_compose: '.devcontainer/docker-compose.yml' # required
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
